sonar.projectKey=el-captain
sonar.projectName=el-captain
sonar.host.url=http://localhost:9000
sonar.sources=apps/web,packages/types
sonar.exclusions=**/node_modules/**,**/.next/**,**/*.test.ts,**/prisma/migrations/**
sonar.tests=apps/web
sonar.test.inclusions=**/*.test.ts
sonar.qualitygate.wait=true
