/** A session row as prisma/models/session returns it (withDetails), for route tests. */
export const sessionRow = (over: Record<string, unknown> = {}) => ({
  id: 'x1',
  coachId: 'k1',
  sportId: 's1',
  venueId: 'v1',
  type: 'GROUP',
  level: 'ALL_LEVELS',
  title: 'Sunrise Flow',
  description: null,
  startsAt: new Date(Date.now() + 86_400_000),
  durationMin: 60,
  price: 350,
  capacity: 12,
  seriesId: null,
  status: 'SCHEDULED',
  cancelledAt: null,
  cancelReason: null,
  createdAt: new Date(0),
  updatedAt: new Date(0),
  sport: { id: 's1', nameEn: 'Yoga', nameAr: 'يوجا', status: 'APPROVED' },
  venue: { id: 'v1', name: 'Club', address: 'St', city: 'Cairo', mapUrl: null, archivedAt: null },
  coach: { id: 'k1', name: 'Mona', coachProfile: { photoPath: null, status: 'ACTIVE' } },
  _count: { bookings: 3 },
  ...over,
});

/** A private request row as prisma/models/private-request returns it (withDetails), for route tests. */
export const requestRow = (over: Record<string, unknown> = {}) => ({
  id: 'r1',
  memberId: 'u1',
  coachId: 'k1',
  venueId: 'v1',
  sportId: 's1',
  startsAt: new Date(Date.now() + 86_400_000),
  durationMin: 60,
  price: 800,
  message: 'Knee rehab',
  status: 'PENDING',
  responseNote: null,
  respondedAt: null,
  sessionId: null,
  createdAt: new Date(0),
  sport: { id: 's1', nameEn: 'Yoga', nameAr: 'يوجا', status: 'APPROVED' },
  venue: { id: 'v1', name: 'Club', address: 'St', city: 'Cairo', mapUrl: null, archivedAt: null },
  member: { id: 'u1', name: 'Ali', email: 'u@x.com', locale: 'ar' },
  coach: { id: 'k1', name: 'Mona', email: 'k@x.com', coachProfile: { locale: 'en' } },
  ...over,
});
